defaults:
  - treeformer
  - _self_

# This config has been tested with B200 GPUs. Set cluster CPU RAM to around 32 GB per CPU.
batch_size: 32
workers: 8
accelerator: auto

train:
    csv_file: /blue/ewhite/veitchmichaelisj/deeplidar/output/folds/all_annotations_train_fold_0.csv
    root_dir: /blue/ewhite/veitchmichaelisj/deeplidar/output
    same_size_images: true
    epochs: 40
    scheduler:
        params:
            T_max: 40

validation:
    csv_file: /blue/ewhite/veitchmichaelisj/deeplidar/output/folds/all_annotations_val_fold_0.csv
    root_dir: /blue/ewhite/veitchmichaelisj/deeplidar/output
    same_size_images: true
    distance_threshold: 10.0

keypoint:
    density_sigma: 3.0
    mae_weight: 0.5
    count_cls_weight: 0.1
    ot_weight: 0.1
    density_l1_weight: 0.05
    sinkhorn_reg: 1.0
    num_of_iter_in_ot: 100
    score_integration_radius: 2
    losses: [count_cls, ot, density_l1]
    norm_cood: true
    enforce_count: true
