defaults:
  - config
  - _self_

architecture: treeformer

batch_size: 32
workers: 8
accelerator: auto

label_dict:
    Bird: 0

num_classes: 1

train:
    csv_file: /blue/ewhite/b.weinstein/bird_detector_retrain/data/train.csv
    root_dir: /blue/ewhite/b.weinstein/bird_detector_retrain/data
    same_size_images: true
    epochs: 40
    scheduler:
        params:
            T_max: 40

validation:
    csv_file: /blue/ewhite/b.weinstein/bird_detector_retrain/data/test.csv
    root_dir: /blue/ewhite/b.weinstein/bird_detector_retrain/data
    same_size_images: true
    distance_threshold: 10.0

keypoint:
    density_sigma: 3.0
    mae_weight: 0.5
    count_cls_weight: 0.1
    ot_weight: 0.1
    density_l1_weight: 0.05
    density_l1_dist_weight: false
    sinkhorn_reg: 1.0
    num_of_iter_in_ot: 100
    score_integration_radius: 2
    losses: [count, count_cls, ot, density_l1]
    norm_cood: true
    enforce_count: true
    log_count_loss: false
